version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    container_name: notiair-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-notiair}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-notiair}
      POSTGRES_DB: ${DB_NAME:-notiair}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-notiair}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

