
services:
  postgres:
    image: postgres:17-alpine
    container_name: notiair-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-notiair}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-notiair}
      POSTGRES_DB: ${DB_NAME:-notiair}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data_notiair:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-notiair}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: notiair-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    # volumes:
    #   - redis_data_notiair:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_notiair:
    driver: local
  redis_data_notiair:
    driver: local

